{% set name = "PyAVM" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 815efcca9bd8c2884799d8cfde537917decf7e6c6e57dd6dbf0e60b18799ee2f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - astropy
    - numpy
    - pillow
    - pytest
  imports:
    - pyavm
  commands:
    - pytest $SP_DIR/pyavm -p no:warnings   # [not win]
    - pytest %SP_DIR%/pyavm -p no:warnings  # [win]

about:
  home: http://astrofrog.github.io/pyavm/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure-Python module to represent, read, and write metadata following the Astronomy Visualization Metadata (AVM) standard
  description: |
    A pure-Python module to represent, read, and write metadata following the
    Astronomy Visualization Metadata (AVM) standard. PyAVM supports Python 2.7
    and 3.5+. No other dependencies are needed simply to read and embed AVM
    meta-data.
  dev_url: https://github.com/astrofrog/pyavm

extra:
  recipe-maintainers:
    - astrofrog
    - pkgw
