travis:
  secure:
    BINSTAR_TOKEN: fNurXBTdYO09GIYpxV00K6Ufp2rY2eDDvLsL/rwe80G4I7kAhuPhlZU4DzIdngKxQGMk3Iiem6cIRnJcxlFwH9WAiOn59+VRO+rG7Qhk0sHpLRb8E1KAKBNKhEpADGJgKVrprBPAZ8+O6nOwwC4cyumGYAZ6Hq26e5tSSHAqGUJJHmXiHxhHG6gzpIzfTZzzWAZnQFiWYeFNSO/OCAao9DxCOHfz4p6qFLEbd2RbJiBI2Yr7DljEB4sfxWDkiPQFWeIDpvgfryG9zPNnlt8Z6swcyfMasU/kP5To2psg92RKrNz/ZWheKA2TlIJWMbX/tjIpIi3XbbHgfvLVwW/MS4jfRqlbnOASl9F+zw4btuB/TWd716JJ+mmt3vUu+Ycg2HZ8BGj02hl0vAHWeUSsyoibo8VR/BeP6c1Rs7qfv9evBPpVwVR0Sr+atl+HQ8cMHfYUXLWJkF/Q+AlK09XfYC7R1ZAqkgRiTrTswClAPT77VTlD+FbUb+rzu0QQXByLPjnPAZsLJSMdsOLrGJY8jQl3R8R2qdPB+IRN9eJOmm79IhXefQc9RmCHCjymAyTyqNsyyz2m8Yw6qV/+WtjPZbO+ZKenbkO09Dt9ECozWMxhOW3zGuuwbVsEIBoe4vyro2SrIuXqqIuu11c9Tq6wqRfQgeQSRvnjT986AHIRzBM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
